
version: 2

models:
    - name: orders_raw
      description: "Raw Orders table with some additional derived columns"
      # columns:
      #   - name: order_id
      #     tests:
      #       - not_null
      #       - unique
      #       - relationships:
      #           to: ref('stg_order_items')
      #           field: order_id
        
      #   - name: customer_id
      #     tests:
      #       - relationships:
      #           field: customer_id
      #           to: ref('stg_customers')
        
      #   - name: staff_id
      #     tests:
      #       - relationships:
      #           field: staff_id
      #           to: ref('stg_staffs')

      #   - name: store_id
      #     tests:
      #       - relationships:
      #           field: store_id
      #           to: ref('stg_stores')

    - name: brands_raw
      description: "Raw Brands table with some additional derived columns"
      # columns:
      #   - name: brand_id
      #     tests:
      #       - not_null
      #       - unique
      #       - relationships:
      #           field: brand_id
      #           to: ref('stg_products')

    - name: categories_raw
      description: "Raw Categories table with some additional derived columns"
      # columns:
      #   - name: category_id
      #     tests:
      #       - not_null
      #       - unique
      #       - relationships:
      #           field: category_id
      #           to: ref('stg_products')

    - name: customers_raw
      description: "Raw Customers table with some additional derived columns"
      # columns:
      #   - name: customer_id
      #     tests:
      #       - not_null
      #       - unique
      #       - relationships:
      #           field: customer_id
      #           to: ref('stg_orders')
    
    - name: order_items_raw
      description: "Raw line item table with some additional derived columns"
      # columns:
      #   - name: order_id
      #     tests:
      #       - not_null
      #       - relationships:
      #           field: order_id
      #           to: ref('stg_orders')
      #   - name: product_id
      #     tests:
      #       - not_null
      #       - relationships:
      #           field: product_id
      #           to: ref('stg_products')
    
    - name: products_raw
      description: "Raw products table with some additional derived columns"
      # columns:
      #   - name: product_id
      #     tests:
      #       - not_null
      #       - unique

    - name: stg_brands
      description: "Stage table for brands."
      
    - name: stg_categories
      description: "Stage table for categories"
      
    - name: stg_customers
      description: "Stage table for customers"
      
    - name: stg_order_items
      description: "Stage table for Order-Items"
      

    - name: stg_orders
      description: "Stage table for orders"
      
    
    - name: stg_products
      description: "Stage table for products"
      
    
    - name: stg_staffs
      description: "Stage table for staffs"
      columns:
        - name: staff_id
          tests:
            - not_null
            - unique

    - name: stg_stocks
      description: "Stage table for stocks"
      columns:
        - name: store_id
          tests:
            - relationships:
                field: store_id
                to: ref('stg_stores')
        
        - name: product_id
          tests:
            - relationships:
                field: product_id
                to: ref('stg_products')
    
    - name: stg_stores
      description: "Stage table for stores"
      columns:
        - name: store_id
          tests:
            - relationships:
                field: store_id
                to: ref('stg_stores')
        
        - name: store_id
          tests:
            - relationships:
                field: store_id
                to: ref('stg_staffs')